require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdapterConfigurationsController do

  # This should return the minimal set of attributes required to create a valid
  # AdapterConfiguration. As you add validations to AdapterConfiguration, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "adapter" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdapterConfigurationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all adapter_configurations as @adapter_configurations" do
      adapter_configuration = AdapterConfiguration.create! valid_attributes
      get :index, {}, valid_session
      assigns(:adapter_configurations).should eq([adapter_configuration])
    end
  end

  describe "GET show" do
    it "assigns the requested adapter_configuration as @adapter_configuration" do
      adapter_configuration = AdapterConfiguration.create! valid_attributes
      get :show, {:id => adapter_configuration.to_param}, valid_session
      assigns(:adapter_configuration).should eq(adapter_configuration)
    end
  end

  describe "GET new" do
    it "assigns a new adapter_configuration as @adapter_configuration" do
      get :new, {}, valid_session
      assigns(:adapter_configuration).should be_a_new(AdapterConfiguration)
    end
  end

  describe "GET edit" do
    it "assigns the requested adapter_configuration as @adapter_configuration" do
      adapter_configuration = AdapterConfiguration.create! valid_attributes
      get :edit, {:id => adapter_configuration.to_param}, valid_session
      assigns(:adapter_configuration).should eq(adapter_configuration)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AdapterConfiguration" do
        expect {
          post :create, {:adapter_configuration => valid_attributes}, valid_session
        }.to change(AdapterConfiguration, :count).by(1)
      end

      it "assigns a newly created adapter_configuration as @adapter_configuration" do
        post :create, {:adapter_configuration => valid_attributes}, valid_session
        assigns(:adapter_configuration).should be_a(AdapterConfiguration)
        assigns(:adapter_configuration).should be_persisted
      end

      it "redirects to the created adapter_configuration" do
        post :create, {:adapter_configuration => valid_attributes}, valid_session
        response.should redirect_to(AdapterConfiguration.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved adapter_configuration as @adapter_configuration" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdapterConfiguration.any_instance.stub(:save).and_return(false)
        post :create, {:adapter_configuration => { "adapter" => "invalid value" }}, valid_session
        assigns(:adapter_configuration).should be_a_new(AdapterConfiguration)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdapterConfiguration.any_instance.stub(:save).and_return(false)
        post :create, {:adapter_configuration => { "adapter" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested adapter_configuration" do
        adapter_configuration = AdapterConfiguration.create! valid_attributes
        # Assuming there are no other adapter_configurations in the database, this
        # specifies that the AdapterConfiguration created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AdapterConfiguration.any_instance.should_receive(:update_attributes).with({ "adapter" => "MyString" })
        put :update, {:id => adapter_configuration.to_param, :adapter_configuration => { "adapter" => "MyString" }}, valid_session
      end

      it "assigns the requested adapter_configuration as @adapter_configuration" do
        adapter_configuration = AdapterConfiguration.create! valid_attributes
        put :update, {:id => adapter_configuration.to_param, :adapter_configuration => valid_attributes}, valid_session
        assigns(:adapter_configuration).should eq(adapter_configuration)
      end

      it "redirects to the adapter_configuration" do
        adapter_configuration = AdapterConfiguration.create! valid_attributes
        put :update, {:id => adapter_configuration.to_param, :adapter_configuration => valid_attributes}, valid_session
        response.should redirect_to(adapter_configuration)
      end
    end

    describe "with invalid params" do
      it "assigns the adapter_configuration as @adapter_configuration" do
        adapter_configuration = AdapterConfiguration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdapterConfiguration.any_instance.stub(:save).and_return(false)
        put :update, {:id => adapter_configuration.to_param, :adapter_configuration => { "adapter" => "invalid value" }}, valid_session
        assigns(:adapter_configuration).should eq(adapter_configuration)
      end

      it "re-renders the 'edit' template" do
        adapter_configuration = AdapterConfiguration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdapterConfiguration.any_instance.stub(:save).and_return(false)
        put :update, {:id => adapter_configuration.to_param, :adapter_configuration => { "adapter" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested adapter_configuration" do
      adapter_configuration = AdapterConfiguration.create! valid_attributes
      expect {
        delete :destroy, {:id => adapter_configuration.to_param}, valid_session
      }.to change(AdapterConfiguration, :count).by(-1)
    end

    it "redirects to the adapter_configurations list" do
      adapter_configuration = AdapterConfiguration.create! valid_attributes
      delete :destroy, {:id => adapter_configuration.to_param}, valid_session
      response.should redirect_to(adapter_configurations_url)
    end
  end

end
